### ISSUE TITLE
2P editing on a small widescreen causes scrollbar horrors

### ISSUE THREAD

**Issue by WaferMouse** [sonicretro/SonLVL#45]
Editing art in 2P mode causes the tile section to be twice as tall, which forces it beyond the window bounds on my screen and causes scrollbars on both axes.  These scrollbars reset their position to the bottom right most times a new chunk/block/tile is selected from the palette.

I'm sure this is working as intended for most people, but it makes working on 2P art difficult for me.  An option/keys to zoom the tile art in/out would be a nice enhancement, but preventing the scroll position from resetting would be an improvement.

**Comment by MainMemory** [comment]
Honestly you may be the only person working with the 2P mode feature.

**Comment by WaferMouse** [comment]
Yeah, I'd gathered ¯\_(ツ)_/¯

**Comment by MainMemory** [comment]
I think the only way to fix it would be to decrease the scale of the tile picture in 2P mode to ensure it takes the same vertical space as the 1P version. I'm not sure if I can actually fix the scrollbar thing because that's the .NET Framework auto-scrolling so the control with focus (the tile selector) is fully visible onscreen.

**Comment by WaferMouse** [comment]
That would be great, I could live with a smaller tile picture, and I doubt anybody would complain about the change so long as it only affected 2P.  Either way, thanks for a response and the work you put into SonLVL!
